name: advent_of_code__dart
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  dotenv: ^4.2.0
  dio: ^5.9.0
  web: ^1.1.1
  html: ^0.15.6
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  test: ^1.28.0

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.9.0
  json_serializable: ^6.11.1
  freezed: ^3.2.3
